image: maven:latest

Build project:
  stage: build
  script:
    - mvn compile -Dspring.profiles.active=DEV

Test project:
  stage: test
  script:
    - mvn test -Dspring.profiles.active=DEV

services:
  - postgres:12.2-alpine



